name: postshiba
description: Dart client for the PostShiba API.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  http: ^1.2.2

dev_dependencies:
  test: ^1.25.8
